!!python/object:__main__.Configuration
repositoryUrl: 'https://github.com/apache/mahout'
repositoryShortname: 'apache/mahout'
repositoryPath: 'C:\Users\nouri\smells_tool\folder1\apache\mahout'
analysisOutputPath: 'C:\Users\nouri\smells_tool\folder1\apache\mahout
aliasPath: 'C:\Users\nouri\smells_tool\folder1\apache\mahout.yml'
aliasSimilarityMaxDistance: 0.75