!!python/object:__main__.Configuration
repositoryUrl: "https://github.com/denious/DevNetworkPython"
repositoryShortname: "denious/DevNetworkPython"
repositoryPath: 'C:\repos\DevNetworkPython'
analysisOutputPath: 'C:\repos\analysisOutput\denious.DevNetworkPython'
aliasPath: 'C:\repos\analysisOutput\aliases\denious.DevNetworkPython.yml'
aliasSimilarityMaxDistance: 0.25